<a href="https://colab.research.google.com/github/goyohanb/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_5%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 5강 - 데이터 저장

## 5-1 CSV 형식 저장

In [4]:
#시작하기 전에 chapter 3에 있는 파일을
#왼쪽 폴더 클릭하고 옮겨둔 다음에 시작하기

import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'database_score': [85, 76, 92, 63, 88],
    'cloudcomputing_score': [78, 82, 95, 70, 84],
    'python_score': [92, 78, 85, 75, 91],
    'watch_rate': [0.95, 0.87, 0.99, 0.80, 0.93]
}
## DataFrame 생성
df = pd.DataFrame(data)
df

## CSV 형식 저장
df.to_csv('student_analysis.csv', encoding='utf-8', index=False)
         #인덱스 012345를 안 보이게 하고 저장 -> index=False
         #저장된 파일은 왼쪽 파일 이모티콘 누르면 확인할 수 있음

## 5-2 JSON 형식 저장

In [8]:
### 라이브러리 임포트
import json
import pandas as pd

data = {
    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": ["프로그래밍", "데이터 분석", "여행"]
}

## json.dump를 이용한 저장
with open('output.json', mode='w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
     #indent 들여쓰기 4칸, 아스키코드를 False로 해서 한글로 저장


## DataFrame을 이용한 저장
df = pd.DataFrame([data])
# df = pd.DataFrame(data)
df.to_json('output_df.json', orient='records', indent=4, force_ascii=False)

# orient='records' 행 단위로 묶어서 저장
# orient='columns' 열 단위로 묶어서 저장.

## 5-3 Pandas Dataframe 데이터 추출

In [18]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)
print(df)

## DataFrame 인덱스 출력
print(df.index) #RangeIndex(start=0, stop=5, step=1)

## DataFrame 컬럼 출력
print(df.columns)

## DataFrame 행 출력
print('###DataFrame 행 출력')
print(df.values.tolist()) # 파이썬의 리스트형태로 바뀜
print(df.values)

## DataFrame 값 출력
print(df.values.flatten())
  # 값들을 하나하나 쭉 나열할 때. 구조를 없애고 다 나열

    이름  학년   학점     학과    동아리
0  김철수   1  4.2   컴퓨터학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5     농학   로봇공학
3  최지훈   4  3.9    교육학   봉사활동
4  정소희   2  3.5  영어영문학   음악감상
RangeIndex(start=0, stop=5, step=1)
Index(['이름', '학년', '학점', '학과', '동아리'], dtype='object')
###DataFrame 행 출력
[['김철수', 1, 4.2, '컴퓨터학', '프로그래밍'], ['이영희', 2, 3.8, '경영학', '독서토론'], ['박민수', 3, 4.5, '농학', '로봇공학'], ['최지훈', 4, 3.9, '교육학', '봉사활동'], ['정소희', 2, 3.5, '영어영문학', '음악감상']]
[['김철수' 1 4.2 '컴퓨터학' '프로그래밍']
 ['이영희' 2 3.8 '경영학' '독서토론']
 ['박민수' 3 4.5 '농학' '로봇공학']
 ['최지훈' 4 3.9 '교육학' '봉사활동']
 ['정소희' 2 3.5 '영어영문학' '음악감상']]
['김철수' 1 4.2 '컴퓨터학' '프로그래밍' '이영희' 2 3.8 '경영학' '독서토론' '박민수' 3 4.5 '농학'
 '로봇공학' '최지훈' 4 3.9 '교육학' '봉사활동' '정소희' 2 3.5 '영어영문학' '음악감상']

## 5-4 DataFrame 생성 방법

In [20]:
import pandas as pd
import json

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## 딕셔너리, csv, json으로 부터 DataFrame 생성
df1 = pd.DataFrame.from_dict(data)
df2 = pd.read_csv('students.csv') #챕터3 파일이 있어야함
df3 = pd.read_json('students.json')

## 세가지 방법 결과 비교  5행 5열
print(df1.shape)
print(df2.shape)
print(df3.shape)

(5, 5)
(5, 5)
(5, 5)

## 5-5 DataFrame 저장 방법

In [22]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## Dataframe 생성
pd = pd.DataFrame(data)


## CSV, JSON 형식으로 저장
df.to_csv('students_scores.csv')
df.to_json('students_scores.json')

## HTML 형식으로 저장
html_table = df.to_html()
with open('students_scores.html', 'w') as f:
    f.write(html_table)

print(html_table)

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>이름</th>
      <th>학년</th>
      <th>학점</th>
      <th>학과</th>
      <th>동아리</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>김철수</td>
      <td>1</td>
      <td>4.2</td>
      <td>컴퓨터학</td>
      <td>프로그래밍</td>
    </tr>
    <tr>
      <th>1</th>
      <td>이영희</td>
      <td>2</td>
      <td>3.8</td>
      <td>경영학</td>
      <td>독서토론</td>
    </tr>
    <tr>
      <th>2</th>
      <td>박민수</td>
      <td>3</td>
      <td>4.5</td>
      <td>농학</td>
      <td>로봇공학</td>
    </tr>
    <tr>
      <th>3</th>
      <td>최지훈</td>
      <td>4</td>
      <td>3.9</td>
      <td>교육학</td>
      <td>봉사활동</td>
    </tr>
    <tr>
      <th>4</th>
      <td>정소희</td>
      <td>2</td>
      <td>3.5</td>
      <td>영어영문학</td>
      <td>음악감상</td>
    </tr>
  </tbody>
</table>

## 5-6 실습 시나리오

## 데이터 수집

In [26]:
import requests

url = "http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty"
api_key = '6bafd83cd117eb113a7c81fea77312de8a2a061809856c86f478aa8bc9121b56'

params = {
    'serviceKey': api_key,
    'returnType': 'json',
    'numOfRows': '100',
    'pageNo': '1',
    'sidoName': '서울',
    'ver': '1.0'
}

## 데이터 수집
response = requests.get(url, params=params)

## 호출 성공/실패 출력
print(response.json()) #자꾸 어떨 땐 잘 불러오는데 안 될 때도 있음. 코드 오류 없다.

#데이터프레임화 하기위해서는 받아온 데이터 구조를 파악할 필요가 있다.
#json 형식이고, items만 필요하니까 그 안에 있는 리스트만 가져와서 데이터 프레임으로 만든다.

{'response': {'body': {'totalCount': 40, 'items': [{'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '21', 'khaiGrade': '2', 'pm25Value': '11', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '중구', 'pm10Grade': '1', 'o3Value': '0.052'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '63', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '24', 'khaiGrade': '2', 'pm25Value': '8', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '한강대로', 'pm10Grade': '1', 'o3Value': '0.045'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '67', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '21', 'khaiGrade': '2', 'pm25Value': '11', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '종로구', 'pm10Grade': '1', 'o3Value': '0.049'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '59', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '25', 'khaiGrade': '2', 'pm25Value': '12', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '청계천로', 'pm10Grade': '1', 'o3Value': '0.040'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '61', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '17', 'khaiGrade': '2', 'pm25Value': '4', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.011', 'stationName': '종로', 'pm10Grade': '1', 'o3Value': '0.042'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '67', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '26', 'khaiGrade': '2', 'pm25Value': '6', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '용산구', 'pm10Grade': '1', 'o3Value': '0.050'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '81', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '24', 'khaiGrade': '2', 'pm25Value': '11', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '광진구', 'pm10Grade': '1', 'o3Value': '0.067'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '76', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '23', 'khaiGrade': '2', 'pm25Value': '15', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.006', 'stationName': '성동구', 'pm10Grade': '1', 'o3Value': '0.060'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '60', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '29', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.029', 'stationName': '강변북로', 'pm10Grade': '1', 'o3Value': '0.041'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.003', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '19', 'khaiGrade': '2', 'pm25Value': '11', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.004', 'stationName': '중랑구', 'pm10Grade': '1', 'o3Value': '0.052'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '68', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '22', 'khaiGrade': '2', 'pm25Value': '15', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '동대문구', 'pm10Grade': '1', 'o3Value': '0.051'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '64', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '18', 'khaiGrade': '2', 'pm25Value': '8', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '홍릉로', 'pm10Grade': '1', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '63', 'so2Value': '0.003', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '17', 'khaiGrade': '2', 'pm25Value': '6', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.003', 'stationName': '성북구', 'pm10Grade': '1', 'o3Value': '0.045'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '58', 'so2Value': '0.001', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '19', 'khaiGrade': '2', 'pm25Value': '9', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '정릉로', 'pm10Grade': '1', 'o3Value': '0.039'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '70', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '21', 'khaiGrade': '2', 'pm25Value': '6', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.002', 'stationName': '도봉구', 'pm10Grade': '1', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '65', 'so2Value': '0.003', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '16', 'khaiGrade': '2', 'pm25Value': '15', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.003', 'stationName': '은평구', 'pm10Grade': '1', 'o3Value': '0.048'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '-', 'so2Value': '0.003', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '20', 'khaiGrade': None, 'pm25Value': '4', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': None, 'so2Flag': None, 'dataTime': '2026-09-20 10:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '서대문구', 'pm10Grade': None, 'o3Value': '0.045'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '62', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '14', 'khaiGrade': '2', 'pm25Value': '8', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.010', 'stationName': '마포구', 'pm10Grade': '1', 'o3Value': '0.043'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '55', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '26', 'khaiGrade': '2', 'pm25Value': '15', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.022', 'stationName': '신촌로', 'pm10Grade': '1', 'o3Value': '0.035'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '65', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '22', 'khaiGrade': '2', 'pm25Value': '13', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '강서구', 'pm10Grade': '1', 'o3Value': '0.048'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '61', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '37', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '공항대로', 'pm10Grade': '1', 'o3Value': '0.042'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '70', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '26', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.003', 'stationName': '구로구', 'pm10Grade': '1', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '65', 'so2Value': '0.003', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '24', 'khaiGrade': '2', 'pm25Value': '11', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '영등포구', 'pm10Grade': '1', 'o3Value': '0.048'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '61', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '19', 'khaiGrade': '2', 'pm25Value': '12', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '영등포로', 'pm10Grade': '1', 'o3Value': '0.043'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '71', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '19', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '동작구', 'pm10Grade': '1', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '62', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '25', 'khaiGrade': '2', 'pm25Value': '18', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '동작대로 중앙차로', 'pm10Grade': '1', 'o3Value': '0.043'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '23', 'khaiGrade': '2', 'pm25Value': '12', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '관악구', 'pm10Grade': '1', 'o3Value': '0.056'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '80', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '18', 'khaiGrade': '2', 'pm25Value': '9', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '강남구', 'pm10Grade': '1', 'o3Value': '0.066'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '31', 'khaiGrade': '2', 'pm25Value': '7', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '서초구', 'pm10Grade': '1', 'o3Value': '0.053'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '68', 'so2Value': '0.003', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '26', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '도산대로', 'pm10Grade': '1', 'o3Value': '0.051'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '62', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '27', 'khaiGrade': '2', 'pm25Value': '11', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '강남대로', 'pm10Grade': '1', 'o3Value': '0.044'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '78', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '23', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.006', 'stationName': '송파구', 'pm10Grade': '1', 'o3Value': '0.063'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '73', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '16', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.004', 'stationName': '강동구', 'pm10Grade': '1', 'o3Value': '0.057'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '62', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '23', 'khaiGrade': '2', 'pm25Value': '12', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.019', 'stationName': '천호대로', 'pm10Grade': '1', 'o3Value': '0.044'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '71', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': '통신장애', 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '30', 'khaiGrade': '2', 'pm25Value': '-', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.004', 'stationName': '금천구', 'pm10Grade': '1', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '59', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '28', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '시흥대로', 'pm10Grade': '1', 'o3Value': '0.040'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '67', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '18', 'khaiGrade': '2', 'pm25Value': '13', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.002', 'stationName': '강북구', 'pm10Grade': '1', 'o3Value': '0.050'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '70', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '28', 'khaiGrade': '2', 'pm25Value': '13', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.004', 'stationName': '양천구', 'pm10Grade': '1', 'o3Value': '0.053'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '70', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '22', 'khaiGrade': '2', 'pm25Value': '9', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.004', 'stationName': '노원구', 'pm10Grade': '1', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '60', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '20', 'khaiGrade': '2', 'pm25Value': '10', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '화랑로', 'pm10Grade': '1', 'o3Value': '0.041'}], 'pageNo': 1, 'numOfRows': 100}, 'header': {'resultMsg': 'NORMAL_CODE', 'resultCode': '00'}}}

## 데이터 프레임 생성

In [32]:
import pandas as pd

## requests로부터 response, body, item 항목 읽기
data = response.json()['response']['body']['items']

print(type(data)) # 데이터 타입
print(len(data)) #데이터 길이
print(data[0]) # 첫 번째 데이터 출

df = pd.DataFrame(data) # 데이터 프레임
df

# df['pm25Grade']  #pm25Flag 컬럼값만 출력

<class 'list'>
40
{'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.2', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '21', 'khaiGrade': '2', 'pm25Value': '11', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-20 16:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '중구', 'pm10Grade': '1', 'o3Value': '0.052'}

,so2Grade,coFlag,khaiValue,so2Value,coValue,pm25Flag,pm10Flag,o3Grade,pm10Value,khaiGrade,...,no2Grade,o3Flag,pm25Grade,so2Flag,dataTime,coGrade,no2Value,stationName,pm10Grade,o3Value
0,1,None,69,0.002,0.2,None,None,2,21,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,중구,1,0.052
1,1,None,63,0.002,0.3,None,None,2,24,2,...,1,None,1,None,2026-09-20 16:00,1,0.013,한강대로,1,0.045
2,1,None,67,0.002,0.2,None,None,2,21,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,종로구,1,0.049
3,1,None,59,0.002,0.2,None,None,2,25,2,...,1,None,1,None,2026-09-20 16:00,1,0.007,청계천로,1,0.040
4,1,None,61,0.002,0.3,None,None,2,17,2,...,1,None,1,None,2026-09-20 16:00,1,0.011,종로,1,0.042
5,1,None,67,0.002,0.2,None,None,2,26,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,용산구,1,0.050
6,1,None,81,0.002,0.3,None,None,2,24,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,광진구,1,0.067
7,1,None,76,0.002,0.2,None,None,2,23,2,...,1,None,1,None,2026-09-20 16:00,1,0.006,성동구,1,0.060
8,1,None,60,0.003,0.5,None,None,2,29,2,...,1,None,1,None,2026-09-20 16:00,1,0.029,강변북로,1,0.041
9,1,None,69,0.003,0.2,None,None,2,19,2,...,1,None,1,None,2026-09-20 16:00,1,0.004,중랑구,1,0.052
10,1,None,68,0.002,0.2,None,None,2,22,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,동대문구,1,0.051
11,1,None,64,0.002,0.3,None,None,2,18,2,...,1,None,1,None,2026-09-20 16:00,1,0.014,홍릉로,1,0.046
12,1,None,63,0.003,0.2,None,None,2,17,2,...,1,None,1,None,2026-09-20 16:00,1,0.003,성북구,1,0.045
13,1,None,58,0.001,0.3,None,None,2,19,2,...,1,None,1,None,2026-09-20 16:00,1,0.012,정릉로,1,0.039
14,1,None,70,0.003,0.3,None,None,2,21,2,...,1,None,1,None,2026-09-20 16:00,1,0.002,도봉구,1,0.054
15,1,None,65,0.003,0.2,None,None,2,16,2,...,1,None,1,None,2026-09-20 16:00,1,0.003,은평구,1,0.048
16,1,None,-,0.003,0.2,None,None,2,20,None,...,1,None,None,None,2026-09-20 10:00,1,0.005,서대문구,None,0.045
17,1,None,62,0.002,0.2,None,None,2,14,2,...,1,None,1,None,2026-09-20 16:00,1,0.010,마포구,1,0.043
18,1,None,55,0.003,0.4,None,None,2,26,2,...,1,None,1,None,2026-09-20 16:00,1,0.022,신촌로,1,0.035
19,1,None,65,0.002,0.2,None,None,2,22,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,강서구,1,0.048
20,1,None,61,0.002,0.3,None,None,2,37,2,...,1,None,1,None,2026-09-20 16:00,1,0.012,공항대로,1,0.042
21,1,None,70,0.002,0.2,None,None,2,26,2,...,1,None,1,None,2026-09-20 16:00,1,0.003,구로구,1,0.054
22,1,None,65,0.003,0.2,None,None,2,24,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,영등포구,1,0.048
23,1,None,61,0.002,0.3,None,None,2,19,2,...,1,None,1,None,2026-09-20 16:00,1,0.012,영등포로,1,0.043
24,1,None,71,0.002,0.2,None,None,2,19,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,동작구,1,0.054
25,1,None,62,0.002,0.3,None,None,2,25,2,...,1,None,1,None,2026-09-20 16:00,1,0.014,동작대로 중앙차로,1,0.043
26,1,None,72,0.002,0.2,None,None,2,23,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,관악구,1,0.056
27,1,None,80,0.002,0.3,None,None,2,18,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,강남구,1,0.066
28,1,None,69,0.002,0.2,None,None,2,31,2,...,1,None,1,None,2026-09-20 16:00,1,0.005,서초구,1,0.053
29,1,None,68,0.003,0.2,None,None,2,26,2,...,1,None,1,None,2026-09-20 16:00,1,0.008,도산대로,1,0.051
30,1,None,62,0.002,0.4,None,None,2,27,2,...,1,None,1,None,2026-09-20 16:00,1,0.014,강남대로,1,0.044
31,1,None,78,0.002,0.2,None,None,2,23,2,...,1,None,1,None,2026-09-20 16:00,1,0.006,송파구,1,0.063
32,1,None,73,0.003,0.3,None,None,2,16,2,...,1,None,1,None,2026-09-20 16:00,1,0.004,강동구,1,0.057
33,1,None,62,0.002,0.4,None,None,2,23,2,...,1,None,1,None,2026-09-20 16:00,1,0.019,천호대로,1,0.044
34,1,None,71,0.003,0.3,통신장애,None,2,30,2,...,1,None,1,None,2026-09-20 16:00,1,0.004,금천구,1,0.054
35,1,None,59,0.003,0.3,None,None,2,28,2,...,1,None,1,None,2026-09-20 16:00,1,0.015,시흥대로,1,0.040
36,1,None,67,0.002,0.2,None,None,2,18,2,...,1,None,1,None,2026-09-20 16:00,1,0.002,강북구,1,0.050
37,1,None,70,0.002,0.2,None,None,2,28,2,...,1,None,1,None,2026-09-20 16:00,1,0.004,양천구,1,0.053
38,1,None,70,0.002,0.2,None,None,2,22,2,...,1,None,1,None,2026-09-20 16:00,1,0.004,노원구,1,0.054
39,1,None,60,0.002,0.3,None,None,2,20,2,...,1,None,1,None,2026-09-20 16:00,1,0.016,화랑로,1,0.041

**굵은 텍스트**## 다양한 형식으로 데이터 저장

In [33]:
## CSV 형식 데이터 저장
df.to_csv('air_pollution.csv', index=False, encoding='utf-8')


## JSON 형식 데이터 저장
df.to_json('air_pollution.json', indent=4, force_ascii=False)
                                     # force_ascii=False 한글 잘 나오도록

## EXCEL 형식 데이터 저장
df.to_excel('air_pollution.xlsx', index=False)

## HTML 형식 데이터 저장
df.to_html('air_pollution.html')